# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58544f24188f535b6ef9d88a8bfb17a38c4be8220d7edd253f9182c155ab767274727062445ec14870fb40efab97f3ca6d8cc059c53439b4c7a7b44931e9c433

test:
  secret_key_base: d2f8701bc63ab354d08006f32c96988c9639983de0dd6a85fb27b13eff71eb5dc63e0fdfa3e2bc17996d6401ec6083ed9d257034c7149badeeb3f01dc52961e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
